### ISSUE TITLE
body content in the DELETE /:key_id endpoint

### ISSUE THREAD

**Issue by motevets** [robinsloan/spring-83#10]
Hey Robin, just read through the new draft.

In reference to the [DELETE /:id endpoint](https://github.com/robinsloan/spring-83/blob/8dacb770ac2a21ed489bc9c3b0164209022fdfef/draft-20220629.md?plain=1#L527). I would caution against relying on a body with a `time` tag for two reasons.

1. The HTTP spec discourages adding a body to a delete request. [RFC 9110 HTTP Semantics 9.3.5 DELETE](https://www.rfc-editor.org/rfc/rfc9110#name-delete). You _could_ make the case that we fall into the carve out of

   > A client SHOULD NOT generate content in a DELETE request unless it is made directly to an origin server that has previously indicated, in or out of band, that such a request has a purpose and will be adequately supported.

   However this would make Spring '83 an odd-duck in HTTP backed protocols, which leads to the next point...

2. Some HTTP clients will drop body content on DELETE requests, especially proxies in an attempt to broadly mitigate request smuggling attacks.

## Counter proposal: no DELETE endpoint
I personally think the DELETE endpoint adds unnecessary complexity to the specification. A board can already be deleted by:

1. wait for the TTL to expire, or
2. make a `POST /:key_id` with only the time body in it

While (2) may not truely delete the board, it does clear it out, and the cleared out board will be propagated to the realm just like any other board. The board's very existence will eventually drop after the TTL expires.

**Comment by motevets** [comment]
I realized that making another issue might be adding more noise that signal. To tie it together, this is related to #6 and #9. Feel free to close this issue if you think the discussion should be happening there.

**Comment by robinsloan** [comment]
Not at all, this is super helpful! I appreciate the perspective (and the cross-linkage).

**Comment by makeworld-the-better-one** [comment]
Yikes, good catch. It can't just be the time that's signed, it has to be some message that's explicitly a delete, and also invalid as a board so it can't be reused. Maybe like `delete 2022-06-30T15:05:40Z`. But yeah, PUTing a blank one also works.

**Comment by robinsloan** [comment]
@rpf By "signed header" do you mean HTTP header? It would have to be "signed header, with the fields in exactly this order, in exactly this format" -- which is of course doable, but pretty "heavy", both in terms of specification and implementation. I think the simplest fix is to require the body to be

```
<time datetime="<timestamp inside a 5 minute window>">DELETE</time>
```

acknowledging that DELETE bodies are, as @motevets notes, fairly ghostly entities.

It's preeetty wonky! But the command is useful. I am mulling.

**Comment by rpj** [comment]
> @rpf By "signed header" do you mean HTTP header? It would have to be "signed header, with the fields in exactly this order, in exactly this format" 

@motevets yup exactly my thinking. it's slightly more machinery I agree but it shouldn't be much of a heavy lift for any of the servers, we already have all the necessary pieces in place it's just a matter of extracting the data from a different spot and verifying that. 

You are right that it could easily be accomplished by sticking a `DELETE` token in the body. However I do worry about the condition you brought up recently (that I admit I had forgotten): `DELETE` requests by-spec shouldn't have a body, which means a _lot_ of proxies will either choke on the request or just strip the body. Both would be bad news bears for us. A signed header avoids that entirely.

**Comment by robinsloan** [comment]
I don't agree with the assessment that DELETE requests can't/shouldn't have bodies. My reading indicates it's okay that they do; it's just that the meaning of those bodies is totally undefined.

@makeworld-the-better-one You're right about re-use, but servers could reject PUTs with this particular content -- essentially, it becomes a "magic word". The wonkiness increases, though.

Anyway, if we are bothering with that kind of special handling, we could just as easily say to servers: "If you receive a blank board with absolutely nothing except the `<time>` element, interpret that as a request to wipe the board from the database." Using the "correct" HTTP verbs is fine when it's useful, but I am absolutely not a purist.

I'm currently leaning towards no DELETE as well, but I will continue to mull.

**Comment by motevets** [comment]
Fun discussion. :)

Anything that wipes a board from a server's databate (regardless of its HTTP verb) will be vulnerable to the "replay attack" that @robinsloan noted earlier. To mitigate this, I think the spec would need to specify something like:

> After a board is deleted, the server MUST keep track that the board was deleted and its time of deletion and respond to all subsequent PUT /:key_id requests with a time before the delete time with 409 CONFLICT and respond to all GET /:key_id with 404 NOT FOUND until such time that a board whose time is greater than the deleted time is PUT to the server.

Personally as a server maintainer, I'd rather just someone PUT me an empty board and keep that on my server for 22 days rather than keep track of a board's deleted state and time.

**Comment by rpj** [comment]
> "If you receive a blank board with absolutely nothing except the <time> element, interpret that as a request to wipe the board from the database." Using the "correct" HTTP verbs is fine when it's useful, but I am absolutely not a purist.

I hadn't even considered this as an option, but I actually think I like this best! Reuses all the PUT machinery as others have noted would be ideal (and it would) but still allows users a way to _properly_ delete a board rather than just pushing an empty one (I realize the distinction is minimal, but I genuinely feel it's important)!

**Comment by rpj** [comment]
Also, while it's very important to enumerate possible attack vectors, I'm not sure it's necessary to try to close the "malicious server" vector within the context of this spec addition (partly because it's really hard to do so): those could/should be mitigated with realm block lists instead, no?

**Comment by robinsloan** [comment]
>  I'm not sure it's necessary to try to close the "malicious server" vector within the context of this spec addition

@rpj Yeah, I agree with this sentiment -- with the proviso that there's a broad swath of malicious activity that might be difficult to detect and attribute, so, if there are simple interventions that make some of that activity impossible, they are probably worthwhile.

**Comment by motevets** [comment]
I don't think the replay attack could be mitigated by the blocklist. The blocklist blocks keys (iirc). The replay attack uses the key of the deleted board to repost an old board.

Let's says Celeste and Doug were having an argument, and Celeste posts something in the heat of moment to her board thats she later regrets. She then asks the Spring '83 server to DELETE and forget her board. Doug, who is still upset with Celeste, doesn't doesn't want her to get off that easy. He still has a copy of her board and it's signature (all publicly available.) _He_ posts it back to the server she deleted it from, and the server happily accepts it. The server admin wants to help, but they can't block Doug from reposting a valid board that was signed with Celeste's key, without blocking Celeste entirely. Every time for the next 22 days that Celleste tries to delete the board, Doug reposts it.

Celeste's only real recourse is to PUT a new board (blank or otherwise) with a newer timestamp to her old board.

FWIW: this is Celeste.
![20210724_165659](https://user-images.githubusercontent.com/777773/176733016-5fef4c0c-7495-456d-ad20-cc7dd2f15803.jpg)

**Comment by rpj** [comment]
> I don't think the replay attack could be mitigated by the blocklist. The blocklist blocks keys (iirc). The replay attack uses the key of the deleted board to repost an old board.

Ah yes you are right here, and I should've specified: I meant a _host_ block list in the realm file (which you are right, does not exist yet in the spec). I do realize that we could be playing forever whackamole with something like that, but the same can be said for a malicious key block list: bad actors have the same ability to generate new keys as we do, after all.

> FWIW: this is Celeste.

😍

**Comment by robinsloan** [comment]
@motevets Oo, thank you for this scenario -- it is so cogent and revealing. I think you've revealed the underlying truth here, something that's deep in the "grain" of the medium: a board must hold its place, with a timestamp, or it can trivially replaced by an old copy of itself.

This is totally clarifying!

**Comment by robinsloan** [comment]
Here's an idea. I realized that "make DELETE request" and "return 404 Not Found" were fused in my mind… but perhaps they don't have to be. Here is a pitch:

1. Publisher makes PUT request for key, with minimal board required by spec: `<time datetime="<timestamp string>">`. No closing tag. That's 38 bytes.

2. Server receives request, stores board.

3. Client makes GET request for key.

4. Server retrieves board, but before returning it, notes that its byte length is 38... and there is only one kind of board that can be only 38 bytes long, a "tombstone" board... so, it returns: 404 Not Found.

I actually think this is less wonky than several of the things I have proposed earlier. Not completely un-wonky, but perhaps workable.

**Comment by scren** [comment]
This idea seems really neat, especially as it would be very simple to implement for the server (as it just is a minimal check while evaluating a GET, and also could be propagated in the same way as other boards). Although, it somewhat bothers me, that </time> is required in ordinary boards, but not this one. Couldn't one just allow "/>" at the end of the time tag in both cases?
This would increase consistency, and open up six extra bytes for ordinary boards. (But would mean that an ordinary board cannot be totally empty, because this would not be distinguishable from a deleted board)

**Comment by robinsloan** [comment]
>  Although, it somewhat bothers me, that </time> is required in ordinary boards, but not this one. Couldn't one just allow "/>" at the end of the time tag in both cases?

Heh heh, @scren, it bothers me, too!

I don't think `<time />` is a valid tag [in HTML5](https://html.spec.whatwg.org/multipage/syntax.html#start-tags). Not that I am the biggest "rahhh, everything must be done exactly as specified" person in the world… but something about the context of writing *a specification* made me want to be a bit more attentive to these details. I think, in practice, `<time />` would work fine, but requiring something that's "incorrect" makes me feel a bit itchy. I wish it didn't, because it would be a neat solution!

Maybe `<time datetime="foo"></time>` -- with no text content -- is the right payload for these minimal pseudo-delete requests. I definitely understand the desire for consistency.
