### ISSUE TITLE
Deny lists and moderation

### ISSUE THREAD

**Issue by motevets** [robinsloan/spring-83#11]
The new draft of the spec says that a server in a swarm must respect the deny list of the realm. There's a certain amount of centralization implied here that makes me uneasy.

For example, if Alice is part of a realm for which Bob controls the denylist, per the spec, Alice is giving Bob the power to decide who can and who cannot post to her server. Is the price of joining a realm, that her server must obey the (hopefully) benevolent dictator Bob and hope he doles out fair punishment?

I'd rather be in cooperation with my federates in who to block. Maybe that's on me to join a realm that has some type of governence that I can get behind, but if possible, I'd like the protocol to encourage that kind of cooperation instead of consolidation.

**Comment by royragsdale** [comment]
An unrelated denylist question. Is it intended to apply to the `GET` method too? It would seem to make sense that if you are preventing publishing (`PUTs`) you would also want to prevent whatever content caused the block in the first place. Currently the spec does not make this explicit.

**Recommendation:** The denylist should apply to all methods (`GET`, `PUT`, `DELETE`) on `/<key>`
