### ISSUE TITLE
Position relative for :host

### ISSUE THREAD

**Issue by raphaelbastide** [robinsloan/spring-83#14]
I am not sure if this is the right place to post this suggestion, but I would suggest adding a `position:relative;` to the default CSS rules`:horst`. In this case, any element with absolute position children of `:host` would not overflow, except if the author wants it.

![image](https://user-images.githubusercontent.com/193122/182812340-2e6ce781-153d-4110-94a1-64e1ef97b35d.png)
`:host` without `position:relative;`

![image](https://user-images.githubusercontent.com/193122/182812919-34e37ed6-7e77-4c22-8b94-7a26ec5d77df.png)
`:host` with `position:relative;`

**Comment by robinsloan** [comment]
That's a great note -- change made in my demo client, and I'll add this to the spec.
