### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by codehangen** [robinsloan/spring-83#16]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by robinsloan** [comment]
Hi there. You might have noticed that the project home page reads: *I'll return with some new offerings sometime in 2023.* There's also a narrative establishing the rough "state of the project" [here](https://www.robinsloan.com/lab/specifying-spring-83/#summer), also linked on the home page.

I'd encourage you to think of projects posted on GitHub less as "active" vs. "inactive" and more as "interesting" vs. "uninteresting". After all, anything can be forked, adapted, extended, and/or invigorated at any time -- anything can be made active by anyone!
