### ISSUE TITLE
Servers as a swarm & realm design

### ISSUE THREAD

**Issue by makeworld-the-better-one** [robinsloan/spring-83#5]
I had this idea up on my board, but I figure putting it here would be a better place so it doesn't go away. If you'd rather not do this in an issue, and would prefer an email or nothing at all, let me know.

## Servers are a swarm
* No client has ties to any one specific server
* Having multiple servers in a realm is just for:
	* Redundancy - like a bittorrent swarm
	* Running software, like some sort of crawler or analyzer	
		* And if you want to run software, you have to contribute to the redundancy. It's great!
* When getting a key, a client picks servers at random to try
* One downside of this is that if a server doesn't respect TTL, then clients will be able to find old keys on that server
* This is solved by having a realm manager (human) who kicks out servers who aren't playing by the rules
* How many servers does the client try before assuming it has the latest update for the requested key?
	* Just one could make sense

---

I feel like this somewhat simplifies the server part of the spec. I really like the idea of clients being detached from servers. It completely removes all the anxiety and decision making of picking a server that comes with federated networks like Mastodon. It also allows client and server developers to be different groups/people, which allows to software ecosystem to grow more rapidly and easily.

**Comment by makeworld-the-better-one** [comment]
That's awesome! I'm pleased to see my board appear on 0l0.lol even though I've never pushed it there.

Personally I would prefer things like this to be specified rather than grow organically, it helps coordinate everyone and start from a common base. But I don't think you made the wrong move or anything, everything's in flux due to being in "draft time", and it's good to have experimentation!

**Comment by robinsloan** [comment]
Ah: for me, the key difference-maker is the way boards are "addressed".

In the home server scenario, my board is generally retrieved from a particular URL. If I am a malicious user and that URL no longer works, it imposes some friction on my followers and me; maybe not a ton! But some. They have to find me again; I have to find a way to announce, "hey, I'm over here now," without access to my board. So, again, it's basically the same as the web's federation model.

In the swarm scenario, my board is retrieved by key from any server at all, so there is zero friction until I am successfully blocked swarm-wide, at which point there is, I guess you could say, total friction.

The availability of intermediate friction and frustration levels is what's appealing to me.

Does that make sense? It's clear in my mind, but I might be communicating it poorly, and/or I might be wrong!

**Comment by makeworld-the-better-one** [comment]
I understand what you're getting at, but I don't think it really does much for the scenario we're imagining. A client could easily be made that tries all the servers in the realm. Or it could be done manually: since the list of servers is public, a user could just try a bunch of different ones until they found the malicious poster they wanted to follow. And so the friction you describe can be greatly reduced. So in my mind this advantage of the home server system is pretty small, which for me doesn't outweigh the cons I initially outlined.

**Comment by motevets** [comment]
I'm enjoying this discussion. I posted this on another issue, but I'd like to reshare it here. It's my thoughts on how federation can actually make moderation more tractable.

The tl;dr is: assuming that servers can reliably assume good faith with their federates, then when a malicious actor gets blocked from one server, the rest of the federation will eventually find out about it when they try to propagate that bad actor's subsequent boards and start seeing `403 Forbidden` responses.

```
Mastodon gets some group decentralized moderation benefit by
1. requiring members to be invited to a Mastodon instance
2. federates blocking servers that don't moderate bad behavior

While Spring '83 doesn't have any mechanism to block bad actors from posting
boards or even spewing out harmful (e.g. hate speech) boards to every known
spring server, federation provides a unique opportunity to allow good
distributed moderation practices.

Lets say there are two federated servers: Alice and Bob, and let's say there's a
malicious actor, who Dr. Evil who has been posting to Bob's server, but Bob is
on vacation and hasn't noticed yet. Alice notices Dr. Evil's boards are harmful
and blocks them from her server. The next time Dr. Evil posts to Bob's server
and the server tries to propagate it, Alice's server responds to the PUT with
403 Forbidden, because posts by that key are forbidden on Alice's server. Bob's
server notices the 403 and /may/ chose to also block Dr. Evil from his server.

If Bob does a poor job of moderating his server or encourages bad behavior,
Alice may decide to un-federate and block Bob's server from propagating to her
server. (Though this would require that /servers/ had their own asymmetric keys
and that they countersigned boards that they were propagating. Otherwise Alice's
server doesn't really know where propagated boards are coming from.)
```

**Comment by makeworld-the-better-one** [comment]
> Because the federation model is FUN

It sure is! Glad you've been thinking about it more.

> ### Opting out
> 
> I do think it's reasonable to let publishers opt out of federation -- perhaps with a `<meta>` tag as we were discussing [in this thread](https://github.com/rpj/spring83/issues/6). A publisher who did so would always have to circulate their full board URL as an identifier -- fine!

If there is no such thing as "home servers", where no client is tied to a server (as proposed in my original comment), then this opt-out is somewhat meaningless, because clients could just eventually request the board from the correct server. Even if you think home servers should exist (which I'd appreciate clarification on), there are still issues:

- Clients could be configured to request specific boards from specific servers, so they wouldn't need to rely on federation
- Federation overall could be harmed by the ability to do this. Imagine a "celebrity" or someone popular, starting a board that everyone wants to read but disabling federation. The "only" way to read it is to join that celeb's home server, consolidating that server's power and reducing federation.
- Clients have to parse two formats for following: bare keys, and URLs. This is not that complex but it's still kind of annoying and finicky. Additionally, users (who may be non-technical) will have to recognize two different formats.

And finally, it just feels weird to me, antithetical to the purpose of the protocol. It's nice for there to be principles and ideas people agree upon by joining the network, rather than creating exceptions for people who disagree that are tricky to implement.

As a side note, the current idea for the meta tag (`<meta name="spring:share" content="false">`) doesn't include the name of the allowed server, so a malicious client could  copy the board of someone who doesn't want federation, and then impersonate them and send PUTs to many servers in network, duplicating the board despite the author's wishes.

> ### Gossip
> 
> In a swarm of, say, 50 servers, I feel like the "full push" is a bit much -- i.e. my server receives a PUT from a publisher, then turns around and executes 50 PUT requests to all the other servers in the swarm.

Yes, definitely I think this should be avoided as it simply does not scale. Since we are okay with eventual consistency, "flood" networks have too many downsides. 

> My concern is a bit selfish: my server implementation is running as a cloud function, and there's a limit on how much work I can do after the primary request. One of my goals for this protocol is to make it tractable & implementable using a wide variety of compute resources, including these cloud functions.

I'm not super familiar with cloud functions, my feeling is that a federated protocol like this shouldn't really be targeting them, but what do I know. Personally I'm more fond of the "Raspberry Pi in my basement" crowd, and think protocols should target that use-case when possible. But if Spring '83 can run in a cloud function, then the more the merrier!

> In my original spec, I proposed a gossip algorithm. I did a bit of simulation work to validate that such an approach might actually work and... I think it will! In fact, a fanout of 5 (i.e. each server sends to 5 random peers) converges the swarm to a shared global state very reliably, even under adversarial conditions, i.e. with peers who accept PUTs but silently refuse to propagate them. In fact, even if 10% or 20% (!) of servers aren't cooperating, the swarm still converges.

Thanks for simulating this, that's great to hear! Maybe the "fanout" (I feel like there's a better term but I forget it now) number could be specified in the realm file, just with the spec recommending a certain value. That way it can be changed as needed, as the realm grows (or shrinks), and as real-world testing defies the simulation.

> The nice thing about the gossip algorithm is that the extra load on each participating server is constant, regardless of the size of the swarm. The load on the network increases, of course -- there's a fair amount of "wasted" chatter as servers gossip new boards to peers that already have them -- but, for a protocol dealing in 2217 byte entities, I feel like bandwidth is almost never going to be the issue.

Definitely. And as I understand it, when a server receives a board from another server, they don't gossip it if they already knew about it. So that would cut down on outbound bandwidth and infinite loops.
 
> I have had to concede that the "difficulty factor" scheme outlined in my original draft spec just isn't going to work. I won't go into all the details here; suffice it to say, it was a cute idea that did not actually achieve its stated goals! 

Fair enough! FWIW I thought it was super cool, despite the impracticality.
 
> But a swarm scenario puts us back into the world of "everything stored everywhere", and, without a difficulty factor, our disks will just keep filling. The only real "lever" is the TTL, which isn't nothing; that, and of course the recourse of the error code. ("429! I'm full! 429, 429!") But, mostly, a Spring '83 server is in the position of saying to the entire internet, "Yeah, sure, store your data here."

A nitpick, but I assume it's more like "store your parseable HTML5 under 2218 bytes here", and new boards require time-consuming key generation. It's still a problem, but it lessens things if you mandate valid HTML5, and of course the key requirement is already in place.

> Sooo -- is that okay? Maybe it is. It will be a long time until this protocol's total disk space consumption amounts to more than tens of megabytes, if it ever does. The mismatch of "infinite invitation" with "finite resource" makes me feel a bit itchy, though, so I thought I'd raise the question.

Yes, it's "itchy" to me as well, it feels uncomfortable to release a protocol that just has that door open, even if it's not a problem in the short term due to lack of popularity. Also, different servers having different disk limits kind of breaks the promise of the swarm/network being eventually consistent, where every server has roughly the same view of all the boards. If one server is only storing 1 GiB but another will store up to 50, that will be a problem.

Maybe one solution is to have the max amount of boards in the realm file. By joining the realm you're committing to storing that many boards/bytes, and the realm admin can kick out your server if it starts returning 429 before the realm has gotten close to the limit. This does introduce race conditions when servers in the realm get close to the limit (for example a server might let in a new board from a client PUT, but then not let in a new board from a server PUT, so server states are not consistent), but at this point I'm comfortable kicking the can down the road. If first realm in Spring '83 (admin'd by you I assume) has a realm limit of 10 million boards, or even 1 million, that's totally fine. It will take a long time to reach that point when you take into account: TTLs, key requirements, spam/abuse management, etc. And if it does reach that point, the community and realm admin can reach a conclusion about what to do about it: increase the limit, switch to a new realm, shut it down and move to Spring '84, whatever works for them.

Re-reading the above, I realize I've still come back to a board limit. But IMO that's fine and reasonable, and it was never an issue to me. It was more that the difficulty factor had issues, and think this idea avoids them.

> Anyway! I'd love to know your thoughts. I realize these issues are totally superfluous for a network of 3 (4?) servers, but I want to arrive at a strategy that will work, at least in theory, for a network of 50, or 500, or more.

I'm right there with you. It's important this can scale and that extensive protocol modifications aren't needed sometime in the future.

---

I've put a fair bit into the realm file with this comment. I don't think that's bad, but if you were to take all these suggestions I think it would make sense for it to be a JSON file instead of plain text, with defined keys like `max_boards`, `fanout`, and  `servers`, or something like that.

**Comment by robinsloan** [comment]
This is an interesting view:

>  There are already use cases for boards that a publisher knows are not appropriate for federation/swarming (such as bot-published boards that get updated frequently but have little value to the network as a whole).

It seems like the distinction is not so much the source -- because of course a bot-published board could be totally valuable -- as the pace, and the sensitivity to the network: a desire not to "waste" time and resources -- which is not misplaced!

I don't have any coherent thoughts about this; I just think it's interesting. The "multiplicative" effect of a swarm architecture is, indeed, what makes me feel most nervous/hesitant. The idea of bot-published boards updating every 10 seconds, gossiping their new versions out into realm-space, makes me feel itchy in the same way that the disk space question does.

("But Robin, that's what computers are FOR" is a reasonable response 😅)

**Comment by scren** [comment]
After thinking slightly about the "home server" question I wondered, if one couldn't imagine clients having some (user specified, probably/possibly private) list of "neighbourhood servers", without any of them being a specific home sever. I imagine for instance my client to have a list of 10 or so servers, which it GETs from, either because they are in different realms or because some of them contain boards that are not federated (e.g. as rpj's weather board) or just to ensure recieving updated boards a bit faster than waiting for updates to arrive at a specific server. Then I in my client could have marked some (but probably not all) of my neighbourhood servers for being used in PUTs. Possibly just one, but maybe multiple, if I want to publish my board in different realms (or for redundancy).
In principle a bit similar to the Home and Backup server lists in The Oakland Follower-Sentinel, but without any priorization, and with the possibility to GET from more servers, than the client PUTs to.

**Comment by robinsloan** [comment]
Thanks for all these comments so far -- they are super helpful.

Another question for you all. So, let's say we've got this JSON document, with all the juicy details about a realm. Where does that document live? Is it okay for it to be maintained on a random server operated by Robin? Should it be a document on GitHub, reachable at `https://raw.githubusercontent.com/foo/bar/realm.json`? Obviously it's going to be maintained by someone(s) -- I'm just wondering what your instincts are in terms of reachability, reliability, and (yes) control.

I apologize for leaning so hard on this group for these questions and solicitations, but... well, you're the group 🤓

**Comment by rpj** [comment]
I’d say GitHub for a few reasons:
- it’s on a third-party, very-high-uptime host so no one person in the
community need worry about keeping this critical piece of infra up seven-9s
- set it up as a separate project just for this file, protect the main
branch to ensure all changes are at least reviewed by one other member,
then invite all of us: that way there’s accountability and traceability but
every single change needn’t go through you

To the latter point it _might_ be worth setting up a GitHub Organization
for all of these projects. They’re free and quite useful as an
organizational tool (lowercase “o”) even for sole developers. I have
multiple myself, and would happily move my server into the community org if
it were available. Helps discovery too; all our related projects in one
place.

**Comment by rpj** [comment]
Also: I know I can only speak for myself but absolutely no apologies
necessary. If anything, thank YOU for including our voices in this!! 🙌

**Comment by makeworld-the-better-one** [comment]
I agree, no apology necessary. It's fun to think about these problems and contribute!

Protocol-wise, I think that all that should be required is that the realm file is available at some HTTPS URL. Servers must ignore the `Content-Type` so that hosts like GitHub can be used. Servers should also follow redirects and probably update their realm file URL(s) for permanent redirects, to allow file moving to happen.

For the first realm, run by you, I would recommend using GitHub, for uptime reasons as @rpj mentions, but mostly because it's super valuable to be able to have the history of the file, and for community members to be able to make PRs.

> \- set it up as a separate project just for this file, protect the main
branch to ensure all changes are at least reviewed by one other member,
then invite all of us: that way there’s accountability and traceability but
every single change needn’t go through you

I disagree, IMO we're just random people on the Internet that Robin shouldn't trust for this. At least to start, I would suggest just creating a repo under your account, that only you have access to, and then just accept and merge PRs at your discretion, and add well-behaved servers as you become aware of them.

> would happily move my server into the community org if
it were available. Helps discovery too; all our related projects in one
place.

This seems strange to me, and although I don't have any public Spring '83 code at the moment, I would not feel comfortable moving it into some sort of org. It's my project, and the only relation is the topic/protocol. Orgs are for when you want to share access to repos easily, not for discoverability. I doubt most of the server/client developers would want to share push access with others just because they're considered "members of the community".

**Comment by rpj** [comment]
@makeworld-the-better-one love the alternative viewpoint, thank you! 

> At least to start, I would suggest just creating a repo under your account, that only you have access to, and then just accept and merge PRs at your discretion, and add well-behaved servers as you become aware of them.

Admittedly it's been awhile since I administered an Org with others but I thought you could still lock a project within an Org down as much as any other project?

Either way, the Org idea is admittedly probably overkill at this point. 

> I doubt most of the server/client developers would want to share push access with others just because they're considered "members of the community".

Can't argue with this as I imagine in the whole you're right, but for an alternative data point: I'm _already_ sharing push access  with a member of this very community on `rpj/spring83`.  🤷 😄 

That said, I admit I'm likely the exception rather than the rule, and the policy for this document should be tailored towards _more_ security and control, so have to concur that maybe my suggestion was too "open", at least to start with.

I do think removing the centralization of control - not because I have a problem with it, but because I feel it's unfairly onerous on one person - will be important eventually. Project management burn out is _real_, even for simple stuff.

**Comment by royragsdale** [comment]
One idea that's been burning around in my head that might apply is "everything is a board".

A realm file is just a board. A server/realms's blocklist is just a board. A client's "springfile/follows" could be just a board. I think there is a cool appeal to the self-hosting/bootstrapping potential to have as much as possible "in-band", especially since we already have some nice cryptographic primitives baked in (e.g. identity/authenticity with signatures).

While I haven't yet noodled out any specifics or put down code to implement this, I think there is likely a scheme where each server has a key (just like any user) and all sign a realm file, or perhaps coordinate to arrive at a shared key. Gotta dust off the old cryptography textbook.

Also, tangentially related in the sense that maybe it helps realize the above, but I believe we have nearly all the necessary mechanisms to encrypt and share messages between servers. For example Server A has an ID key (IdPublic/IdSecret) and a "mail box" key. It has the keys so it knows it has ownership. It publishes/announces/broadcasts the Mail Public Key to the world, so that anyone knows where to post to it. Server A accepts ephemeral PUTs for this key, (e.g. doesn't persist them). Server A decides (however) to allow Server B into the realm. When Server B then posts to the Server A Mail Key, with a message encrypted to IdPublic, and signed by B IdSecret (just as it it were posting to it's own board). Server A receives this message and is the only one able to decrypt it, and processes the message. Since it is coming from a trusted sender (e.g. B in the realm), it can then make decisions on that message/command/etc, or establish a non-ephemeral channel with B, over other keysets, or...

That makes it all sound rather complicated, but that is just my poor half baked attempt to get the idea out. I bet the mathematicians have some elegant stuff to solve this and we can re-embrace some of the cypherpunk crypto-means-cryptography vibe that the difficulty calculation was aiming for.

**Comment by rpj** [comment]
@royragsdale love this! especially the "as much as possible 'in-band'": we should definitely be "self-hosting"/"in-band" if we can! as you rightly note, the protocol is already perfect for this. heck I've even baked JSON into my bot-boards and made it trivial to extract... 

Does seem like we'd want some TTL exceptions for the service-critical boards though right? Just to ensure we don't accidentally forget to refresh them (or our automation that is supposed to do so breaks) and we end up breaking the network with a failure mode akin to "oh crap someone forgot to renew the SSL cert didn't they?!" 😆

**Comment by robinsloan** [comment]
> This all seems pretty unrelated to the original discussion, so it might be more helpful to spin this out into another issue.

I disagree -- it's interesting & generative to have it here, and I appreciate the (provocative!) idea.

**Comment by royragsdale** [comment]
@makeworld-the-better-one, thank you for the perspective.

> encrypted communications being illegal on ham radio frequencies

That's really interesting, I didn't realize that.

I made a new issue over on my implementation to continue exploring this topic. As you rightly point out, it's totally [possible](https://words.filippo.io/using-ed25519-keys-for-encryption/) to convert keys and I think that's pretty exciting. Happy to continue the discussion there.
