### ISSUE TITLE
Reconsider `Spring-Version` header requirement for client GET requests

### ISSUE THREAD

**Issue by royragsdale** [robinsloan/spring-83#7]
## Issue

Currently the spec requires client GET requests to include a `Spring-Version` header:

- [GET /](https://github.com/robinsloan/spring-83-spec/blob/main/draft-20220609.md?plain=1#L325)
- [GET /key](https://github.com/robinsloan/spring-83-spec/blob/main/draft-20220609.md?plain=1#L350)

Interpreted strictly this would prevent browsing to pages with standard web browsers (which would not set this header).

Current server implementations seem to be permissive in this regard, using the "/" page to support general discovery (from a browser) and "direct" browser access to boards:
- [bogbody.biz](https://bogbody.biz/db8a22f49c7f98690106cc2aaac15201608db185b4ada99b5bf4f222883e1223)
- [0l0.lol](https://0l0.lol/db8a22f49c7f98690106cc2aaac15201608db185b4ada99b5bf4f222883e1223)
- [spring83.kindrobot.ca](https://spring83.kindrobot.ca/db8a22f49c7f98690106cc2aaac15201608db185b4ada99b5bf4f222883e1223)

## Discussion:
Since neither of the GET requests place any special requirements on the client (e.g. no content or other mandatory fields), There is little gained from requiring the header and distinguishing between spring 83 clients and other standard HTTP clients.

## Recommendation:

Remove the MUST requirement for clients to include a `Spring-Version` header. Either remove entirely or reduce to a  SHOULD. This would allow a slight bridge over to other HTTP clients (e.g. browsers) for discovery and make the Springiverse more generally accessible.

The only (minor) complexity that this perhaps introduces is a lack of parity between the expected headers for client requests. For example, maybe the `PUT /key` requests still needs such a header to support future versions of the spec. However this would make more sense because publishing can only happen from a conforming client. Similarly replies from a server the `Spring-Version` header makes more sense and don't impose any restrictions.

**Comment by robinsloan** [comment]
What a terrific recommendation; I totally agree, and I'll wrap it into the next version of the specification.

Thanks for taking the time to notice & articulate this!

**Comment by royragsdale** [comment]
Thank you!

**Comment by makeworld-the-better-one** [comment]
I think that's a great idea, I've noticed the same thing, how broken they look in browser. The only catch is that that this would break iframe embedding, but maybe that's fine since I'm pretty sure the CSS still wouldn't work in an iframe anyway. Servers could optionally implement `/embed/<key>` or something for that purpose anyway.

**Comment by rpj** [comment]
@robinsloan love love love this idea! Especially the part of gracefully degrading the user experience when it's possible to detect (via the lack of Spring-Version, for example) that they're not using a "Spring client" but rather a regular 'ol browser. It could still be valuable to have an explicit, separate endpoint to serve the transformed document from as @makeworld-the-better-one suggests, but the graceful degradation of the user experience would _really_ improve the bare-browser use case. 👍 💯

**Comment by royragsdale** [comment]
Addressed in the new spec: https://github.com/robinsloan/spring-83/blob/main/draft-20220629.md#serving-web-browsers
